---
- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
  - name: Copy file to tomcat
    copy:
      src: '/var/snap/jenkins/5042/workspace/webapp2/target/webapp2.war'
      dest: '/opt/tomcat/webapps/webapp2.war'
      remote_src: no
  - name: Restart Tomcat
    shell: |
      /opt/tomcat/bin/shutdown.sh
      /opt/tomcat/bin/startup.sh
      
